-- MySQL Script generated by MySQL Workbench
-- sam. 05 oct. 2019 23:56:42 CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering
-- Author: HADJI Mohamed Allam

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema goodtime
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `goodtime` ;

-- -----------------------------------------------------
-- Schema goodtime
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `goodtime` ;
USE `goodtime` ;

-- -----------------------------------------------------
-- Table `goodtime`.`addresses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `goodtime`.`addresses` ;

CREATE TABLE IF NOT EXISTS `goodtime`.`addresses` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `number` INT(4) NULL,
  `street` VARCHAR(100) NOT NULL,
  `complement` VARCHAR(100) NULL,
  `post_code` INT(6) NOT NULL,
  `city` VARCHAR(30) NOT NULL,
  `latitude` FLOAT NULL,
  `longitude` FLOAT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `goodtime`.`pictures`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `goodtime`.`pictures` ;

CREATE TABLE IF NOT EXISTS `goodtime`.`pictures` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `path` VARCHAR(200) NOT NULL,
  `created_by` INT NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_by` INT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `is_active` TINYINT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `goodtime`.`user_types`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `goodtime`.`user_types` ;

CREATE TABLE IF NOT EXISTS `goodtime`.`user_types` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `goodtime`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `goodtime`.`users` ;

CREATE TABLE IF NOT EXISTS `goodtime`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(45) NULL,
  `username` VARCHAR(45) NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `password` VARCHAR(50) NOT NULL,
  `token` VARCHAR(255) NULL,
  `user_types_id` INT NOT NULL,
  `pictures_id` INT NULL,
  `favorite_item` INT NULL,
  `max_price` FLOAT NULL,
  `favorite_transportation` INT NULL,
  `created_by` INT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_by` INT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `is_active` TINYINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_users_pictures1_idx` (`pictures_id` ASC),
  INDEX `fk_users_user_type1_idx` (`user_types_id` ASC),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC),
  CONSTRAINT `fk_users_pictures1`
    FOREIGN KEY (`pictures_id`)
    REFERENCES `goodtime`.`pictures` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_user_type1`
    FOREIGN KEY (`user_types_id`)
    REFERENCES `goodtime`.`user_types` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `goodtime`.`bars`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `goodtime`.`bars` ;

CREATE TABLE IF NOT EXISTS `goodtime`.`bars` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` TEXT NULL,
  `addresses_id` INT NOT NULL,
  `users_id` INT NOT NULL,
  `phone` VARCHAR(45) NULL,
  `type` VARCHAR(45) NULL,
  `created_by` INT NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_by` INT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `is_active` TINYINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_establishments_adresses1_idx` (`addresses_id` ASC),
  INDEX `fk_bars_users1_idx` (`users_id` ASC),
  CONSTRAINT `fk_establishments_adresses1`
    FOREIGN KEY (`addresses_id`)
    REFERENCES `goodtime`.`addresses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_bars_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `goodtime`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `goodtime`.`favorite_bars`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `goodtime`.`favorite_bars` ;

CREATE TABLE IF NOT EXISTS `goodtime`.`favorite_bars` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `users_id` INT NOT NULL,
  `bars_id` INT NOT NULL,
  `created_by` INT NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_by` INT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `is_active` TINYINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_favorites_users1_idx` (`users_id` ASC),
  INDEX `fk_favorites_establishments1_idx` (`bars_id` ASC),
  CONSTRAINT `fk_favorites_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `goodtime`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_favorites_establishments1`
    FOREIGN KEY (`bars_id`)
    REFERENCES `goodtime`.`bars` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `goodtime`.`groups`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `goodtime`.`groups` ;

CREATE TABLE IF NOT EXISTS `goodtime`.`groups` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `created_by` INT NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_by` INT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `is_active` TINYINT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `goodtime`.`user_groups`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `goodtime`.`user_groups` ;

CREATE TABLE IF NOT EXISTS `goodtime`.`user_groups` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `users_id` INT NOT NULL,
  `groups_id` INT NOT NULL,
  `status` VARCHAR(3) NOT NULL,
  `created_by` INT NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_by` INT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `is_active` TINYINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_user_group_users_idx` (`users_id` ASC),
  INDEX `fk_user_group_groups1_idx` (`groups_id` ASC),
  CONSTRAINT `fk_user_group_users`
    FOREIGN KEY (`users_id`)
    REFERENCES `goodtime`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_group_groups1`
    FOREIGN KEY (`groups_id`)
    REFERENCES `goodtime`.`groups` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `goodtime`.`good_times`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `goodtime`.`good_times` ;

CREATE TABLE IF NOT EXISTS `goodtime`.`good_times` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `groups_id` INT NULL,
  `bars_id` INT NOT NULL,
  `date` DATE NOT NULL,
  `is_booking` TINYINT NULL DEFAULT 0,
  `number_of_participants` INT NULL,
  `status` VARCHAR(3) NOT NULL,
  `refusal_purpose` VARCHAR(50) NULL,
  `created_by` INT NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_by` INT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `is_active` TINYINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_bookings_groups1_idx` (`groups_id` ASC),
  INDEX `fk_bookings_establishments1_idx` (`bars_id` ASC),
  CONSTRAINT `fk_bookings_groups1`
    FOREIGN KEY (`groups_id`)
    REFERENCES `goodtime`.`groups` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_bookings_establishments1`
    FOREIGN KEY (`bars_id`)
    REFERENCES `goodtime`.`bars` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `goodtime`.`items`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `goodtime`.`items` ;

CREATE TABLE IF NOT EXISTS `goodtime`.`items` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` TEXT NULL,
  `is_food` TINYINT NULL DEFAULT 0,
  `contains_alcohol` TINYINT NULL DEFAULT 0,
  `contains_allergen` TINYINT NULL DEFAULT 0,
  `created_by` INT NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_by` INT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `is_active` TINYINT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `goodtime`.`menus`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `goodtime`.`menus` ;

CREATE TABLE IF NOT EXISTS `goodtime`.`menus` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '\n',
  `menu_section` VARCHAR(45) NOT NULL,
  `bars_id` INT NOT NULL,
  `created_by` INT NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_by` INT NULL,
  `date_edit` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `is_active` TINYINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_menus_establishments1_idx` (`bars_id` ASC),
  CONSTRAINT `fk_menus_establishments1`
    FOREIGN KEY (`bars_id`)
    REFERENCES `goodtime`.`bars` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `goodtime`.`menu_items`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `goodtime`.`menu_items` ;

CREATE TABLE IF NOT EXISTS `goodtime`.`menu_items` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `menus_id` INT NOT NULL,
  `items_id` INT NOT NULL,
  `price` FLOAT NOT NULL,
  `created_by` INT NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_by` INT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `is_active` TINYINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_menu_item_menus1_idx` (`menus_id` ASC),
  INDEX `fk_menu_item_items1_idx` (`items_id` ASC),
  CONSTRAINT `fk_menu_item_menus1`
    FOREIGN KEY (`menus_id`)
    REFERENCES `goodtime`.`menus` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_menu_item_items1`
    FOREIGN KEY (`items_id`)
    REFERENCES `goodtime`.`items` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `goodtime`.`discounts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `goodtime`.`discounts` ;

CREATE TABLE IF NOT EXISTS `goodtime`.`discounts` (
  `id` INT NOT NULL,
  `menu_items_id` INT NOT NULL,
  `amount` FLOAT NOT NULL,
  `begin_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `end_at` TIMESTAMP NULL,
  `created_by` INT NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_by` INT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `is_active` TINYINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_discounts_menu_item1_idx` (`menu_items_id` ASC),
  CONSTRAINT `fk_discounts_menu_item1`
    FOREIGN KEY (`menu_items_id`)
    REFERENCES `goodtime`.`menu_items` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `goodtime`.`ratings`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `goodtime`.`ratings` ;

CREATE TABLE IF NOT EXISTS `goodtime`.`ratings` (
  `id` INT NOT NULL,
  `users_id` INT NOT NULL,
  `bars_id` INT NOT NULL,
  `mark` FLOAT NULL,
  `comment` VARCHAR(45) NULL,
  `created_by` INT NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_by` INT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `is_active` TINYINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_ratings_users1_idx` (`users_id` ASC),
  INDEX `fk_ratings_establishments1_idx` (`bars_id` ASC),
  CONSTRAINT `fk_ratings_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `goodtime`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ratings_establishments1`
    FOREIGN KEY (`bars_id`)
    REFERENCES `goodtime`.`bars` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `goodtime`.`events`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `goodtime`.`events` ;

CREATE TABLE IF NOT EXISTS `goodtime`.`events` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` TEXT NOT NULL,
  `bars_id` INT NOT NULL,
  `date` TIMESTAMP NOT NULL,
  `created_by` INT NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_by` INT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `is_active` TINYINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_events_establishments1_idx` (`bars_id` ASC),
  CONSTRAINT `fk_events_establishments1`
    FOREIGN KEY (`bars_id`)
    REFERENCES `goodtime`.`bars` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `goodtime`.`bar_pictures`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `goodtime`.`bar_pictures` ;

CREATE TABLE IF NOT EXISTS `goodtime`.`bar_pictures` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `bars_id` INT NOT NULL,
  `pictures_id` INT NOT NULL,
  `is_main` TINYINT NULL DEFAULT 0,
  `created_by` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_by` INT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `is_active` TINYINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_bar_pictures_bars1_idx` (`bars_id` ASC),
  INDEX `fk_bar_pictures_pictures1_idx` (`pictures_id` ASC),
  CONSTRAINT `fk_bar_pictures_bars1`
    FOREIGN KEY (`bars_id`)
    REFERENCES `goodtime`.`bars` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_bar_pictures_pictures1`
    FOREIGN KEY (`pictures_id`)
    REFERENCES `goodtime`.`pictures` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `goodtime`.`schedules`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `goodtime`.`schedules` ;

CREATE TABLE IF NOT EXISTS `goodtime`.`schedules` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `bars_id` INT NOT NULL,
  `weekday` VARCHAR(3) NOT NULL,
  `open` TINYINT NULL DEFAULT 1,
  `is_hh` TINYINT NULL DEFAULT 0,
  `hour` TIME NOT NULL,
  `notes` TEXT NULL,
  `created_by` INT NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_by` INT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `is_active` TINYINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_scheduls_bars1_idx` (`bars_id` ASC),
  CONSTRAINT `fk_scheduls_bars1`
    FOREIGN KEY (`bars_id`)
    REFERENCES `goodtime`.`bars` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `goodtime`.`special_schedules`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `goodtime`.`special_schedules` ;

CREATE TABLE IF NOT EXISTS `goodtime`.`special_schedules` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `bars_id` INT NOT NULL,
  `begin_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `end_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `new_opening_hours` TIME NULL,
  `new_closing_hours` TIME NULL,
  `is_just_closed` TINYINT NULL DEFAULT 0,
  `created_by` INT NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_by` INT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `is_active` TINYINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_special_schedule_bars1_idx` (`bars_id` ASC),
  CONSTRAINT `fk_special_schedule_bars1`
    FOREIGN KEY (`bars_id`)
    REFERENCES `goodtime`.`bars` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
